### ISSUE TITLE
Definir Fuente de Datos

### ISSUE THREAD

**Issue by fjavieralba** [codeforspain/ds-pib#1]
Después de investigar un poco, parece que los candidatos son:
- Banco Mundial
- OECD
- INE

Las webs del Banco Mundial y la OECD tienen API. En el caso de la OECD, hay datos en la web sobre el PIB (GDP en inglés), pero no he conseguido accederlos via API.

Lo más prometedor que he encontrado hasta ahora es esta llamada a la API del Banco Mundial:

http://api.worldbank.org/countries/ESP/indicators/NY.GDP.MKTP.CD?per_page=100&date=1960:2016&format=json

Estos datos parecen coincidir con lo que muestra Google en su widget de resultados de búsqueda: https://www.google.es/search?q=spain+gdp&oq=spain+gdp

**Comment by fesja** [comment]
Hola @fjavieralba,

¿El Banco Mundial incluye los datos del PIB trimestrales al menos y por comunidades y ciudades? Deberíamos conseguir también esos, tal y como recomendaba una guía que puso @jpaulet. 

Si hay que ir al INE, habla con los otros que también tienen que sacar datos del INE (Poblacion) porque igual podéis reutilizar el script apuntando a diversos sitios.

**Comment by jpaulet** [comment]
Buenas, 

Yo tengo controlado esto para el PIB: http://www.ine.es/jaxi/menu.do;jsessionid=F758DCFF64666745F992CFDB87498047.jaxi01?type=pcaxis&path=%2Ft35%2Fp010&file=inebase&L=0

INE + PC-axis (se reutilizar el script de poblacion) o el de PopulateTools (https://github.com/PopulateTools/ruby-px)
Pero los documentos son complejos y se deberan limpiar bien. 

También hay: https://es.wikipedia.org/wiki/Anexo:Provincias_de_Espa%C3%B1a_por_PIB_per_capita pero es solo del 2011 y sin mucho desagregado.

**Comment by fjavieralba** [comment]
@fesja no, tanto en el Banco Mundial como en OECD, los datos son agregados por país, no he visto que lleguen a nivel de comunidad autónoma. En el caso de OECD sí he visto datos trimestrales, pero no a traves de API. 

Así que, parece claro que para tener el dato trimestral y por comunidad autónoma, hay que ir al INE.

@jpaulet gracias por el link, he visto que también hay opción de descargar los datos en formato CSV, que probablemente sea más fácil de tratar que PC-axis.

por ejemplo:

`P.I.B. a precios de mercado y valor añadido bruto a precios básicos por ramas de actividad: Precios corrientes por comunidades y ciudades autónomas y periodo` : http://www.ine.es/jaxi/files/_px/es/csv/t35/p010/base2010/homoge/l0/01001.px?nocab=1

**Comment by fesja** [comment]
@fjavieralba @jpaulet ¿qué tal va el avance? ¿tenéis dudas en algo? El script del INE ya lo han publicado en https://github.com/codeforspain/ds-poblacion/

**Comment by fjavieralba** [comment]
Hola @fesja! sorry, que esta semana he andado bastante liado 😞 

Esta próxima semana espero poder darle un empujón!

**Comment by fjavieralba** [comment]
Bueno, claramente la mejor opción para la fuente de datos es el INE, cierro este issue
